### ISSUE TITLE
Result links are dead

### ISSUE THREAD

**Issue by Qendolin** [chrismile/PixelSyncOIT#1]
The links to the results and the video do not work. Instead they show the error `Der Link "59f626a6" zeigt auf eine nicht existierende Datei oder Ordner, oder es fehlen die NTFS-Berechtigungen zum Lesen.`.

**Comment by K3rn1n4tor** [comment]
Thank you very much Quendolin for this hint.
I've updated the links again. The results can be downloaded from the TUM's webpage (and will be included directly into the repository in the future). The video was uploaded to Youtube and will be modified in the future, maybe also with voice recording.
