### ISSUE TITLE
Please add support for Visual Studio

### ISSUE THREAD

**Issue by krNeko9t** [chrismile/PixelSyncOIT#3]
Very effective tools for exploration of transparency rendering, but i've been struggling building it on Windows for days. I tried MSYS2 and install all the dependencies you required, but it won't work( this project and the SGL both). I cmake SGL under MSYS2 MinGW64, it shows warnings about GLEW/GLM, and when I type make, it fails at the link state, have you encounter this situation when try it on Windows? Please help me out or tells how to do for Visual Studio. Thx anyway.

**Comment by chrismile** [comment]
Thanks a lot for reporting this bug! I hope it should be fixed now with my recent commits. It seems like some things have changed in the CMake config of newer versions of GLEW. Unfortunately, I'm only using Linux most of the time, so sometimes Windows-specific bugs might happen.

Anyways, I hope you should be able to compile both sgl and this program now using MSYS2 + MinGW64.

I think that in theory there should be (hopefully) nothing that directly blocks Visual Studio support, but getting all dependencies to work on Visual Studio might be considerably more work than just using MSYS2. So I don't currently plan to add any tutorial on how to compile the program with Visual Studio.

**Comment by krNeko9t** [comment]
Problem fixed, thank you for rapidly responding!  And there is one minor problem while running the program, it seems that the directory "./data/*" were not recognized by the program, and have to be copied manually to ./build ( "ln -S" on Windows seems does the same thing).

**Comment by chrismile** [comment]
Closing this issue, as the successor of PixelSyncOIT (LineVis, https://github.com/chrismile/LineVis) finally has support for Visual Studio/MSVC.
